# Generated by Django 4.1.2 on 2022-12-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emaii',
            new_name='email',
        ),
    ]
